# Configuration de la source de données (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_rattrapage?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8082

# Configuration JWT
unif.app.jwtSecret=votreSuperCleSecreteDePlusDe64CaracteresPourLaSecuriteDuProjetJEE2024
unif.app.jwtExpirationMs=86400000
